import type { SubjectPack, SubjectTemplate } from "../../../shared/types";

const subjects: SubjectTemplate[] = [
  // Mata Kuliah Umum (MKU) - General Education
  {
    id: "pancasila",
    name: "Pancasila",
    color: "#dc2626",
    description: "Pendidikan ideologi dan karakter bangsa Indonesia",
    category: "social",
    isCore: true,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Pancasila",
      id: "Pancasila",
    },
    tags: ["ideologi", "karakter", "bangsa", "moral"],
    defaultSchedule: {
      day: ["monday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "agama",
    name: "Pendidikan Agama",
    color: "#6366f1",
    description: "Pendidikan agama sesuai keyakinan mahasiswa",
    category: "religious",
    isCore: true,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Religious Education",
      id: "Pendidikan Agama",
    },
    tags: ["agama", "spiritual", "etika", "moral"],
    defaultSchedule: {
      day: ["tuesday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "kewarganegaraan",
    name: "Pendidikan Kewarganegaraan",
    color: "#dc2626",
    description: "Wawasan kebangsaan dan kewarganegaraan",
    category: "social",
    isCore: true,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Citizenship Education",
      id: "Pendidikan Kewarganegaraan",
    },
    tags: ["wawasan", "kebangsaan", "konstitusi", "demokrasi"],
    defaultSchedule: {
      day: ["wednesday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "bahasa-indonesia-kuliah",
    name: "Bahasa Indonesia",
    color: "#dc2626",
    description: "Bahasa Indonesia ilmiah dan akademik",
    category: "language",
    isCore: true,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Indonesian Language",
      id: "Bahasa Indonesia",
    },
    tags: ["akademik", "ilmiah", "karya-tulis", "komunikasi"],
    defaultSchedule: {
      day: ["thursday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "bahasa-inggris-kuliah",
    name: "Bahasa Inggris",
    color: "#10b981",
    description: "English for Academic Purposes (EAP)",
    category: "language",
    isCore: true,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "English",
      id: "Bahasa Inggris",
    },
    tags: ["academic", "research", "presentation", "toefl"],
    defaultSchedule: {
      day: ["friday"],
      duration: 100,
      frequency: "weekly",
    },
  },

  // Mata Kuliah Dasar Keilmuan (MKDK) - Basic Sciences
  {
    id: "matematika-dasar",
    name: "Matematika Dasar",
    color: "#3b82f6",
    description: "Kalkulus dan matematika untuk sains dan teknik",
    category: "mathematics",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Basic Mathematics",
      id: "Matematika Dasar",
    },
    tags: ["kalkulus", "aljabar-linear", "diferensial", "integral"],
    defaultSchedule: {
      day: ["monday", "wednesday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "fisika-dasar",
    name: "Fisika Dasar",
    color: "#dc2626",
    description: "Mekanika, termodinamika, dan gelombang",
    category: "science",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Basic Physics",
      id: "Fisika Dasar",
    },
    tags: ["mekanika", "termodinamika", "elektromagnetik", "optik"],
    defaultSchedule: {
      day: ["tuesday", "thursday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "kimia-dasar",
    name: "Kimia Dasar",
    color: "#7c3aed",
    description: "Kimia umum dan anorganik dasar",
    category: "science",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Basic Chemistry",
      id: "Kimia Dasar",
    },
    tags: ["kimia-umum", "anorganik", "stoikiometri", "termokimia"],
    defaultSchedule: {
      day: ["wednesday", "friday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "biologi-dasar",
    name: "Biologi Dasar",
    color: "#166534",
    description: "Biologi sel, genetika, dan ekologi",
    category: "science",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Basic Biology",
      id: "Biologi Dasar",
    },
    tags: ["sel", "genetika", "evolusi", "ekologi"],
    defaultSchedule: {
      day: ["monday", "thursday"],
      duration: 100,
      frequency: "weekly",
    },
  },

  // Mata Kuliah Teknologi Informasi
  {
    id: "algoritma-pemrograman",
    name: "Algoritma dan Pemrograman",
    color: "#4338ca",
    description: "Dasar algoritma dan pemrograman komputer",
    category: "technology",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Algorithms and Programming",
      id: "Algoritma dan Pemrograman",
    },
    tags: ["algoritma", "programming", "logic", "problem-solving"],
    defaultSchedule: {
      day: ["tuesday", "friday"],
      duration: 150,
      frequency: "weekly",
    },
  },
  {
    id: "struktur-data",
    name: "Struktur Data",
    color: "#3730a3",
    description: "Array, linked list, stack, queue, tree, graph",
    category: "technology",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Data Structures",
      id: "Struktur Data",
    },
    prerequisites: ["algoritma-pemrograman"],
    tags: ["array", "linked-list", "tree", "graph"],
    defaultSchedule: {
      day: ["monday", "wednesday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "basis-data",
    name: "Basis Data",
    color: "#059669",
    description: "Desain database dan SQL",
    category: "technology",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Database",
      id: "Basis Data",
    },
    tags: ["database", "sql", "normalisasi", "erd"],
    defaultSchedule: {
      day: ["thursday"],
      duration: 150,
      frequency: "weekly",
    },
  },

  // Mata Kuliah Sosial dan Humaniora
  {
    id: "statistika",
    name: "Statistika",
    color: "#0f766e",
    description: "Statistika deskriptif dan inferensial",
    category: "mathematics",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Statistics",
      id: "Statistika",
    },
    tags: ["deskriptif", "inferensial", "probabilitas", "hipotesis"],
    defaultSchedule: {
      day: ["wednesday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "metodologi-penelitian",
    name: "Metodologi Penelitian",
    color: "#374151",
    description: "Metode penelitian kuantitatif dan kualitatif",
    category: "social",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Research Methodology",
      id: "Metodologi Penelitian",
    },
    tags: ["kuantitatif", "kualitatif", "hipotesis", "analisis"],
    defaultSchedule: {
      day: ["friday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "ekonomi-dasar",
    name: "Ekonomi Dasar",
    color: "#d97706",
    description: "Mikroekonomi dan makroekonomi dasar",
    category: "social",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Basic Economics",
      id: "Ekonomi Dasar",
    },
    tags: ["mikroekonomi", "makroekonomi", "pasar", "inflasi"],
    defaultSchedule: {
      day: ["monday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "psikologi-umum",
    name: "Psikologi Umum",
    color: "#7c2d12",
    description: "Pengantar psikologi dan perilaku manusia",
    category: "social",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "General Psychology",
      id: "Psikologi Umum",
    },
    tags: ["perilaku", "kognitif", "emosi", "pembelajaran"],
    defaultSchedule: {
      day: ["tuesday"],
      duration: 100,
      frequency: "weekly",
    },
  },

  // Mata Kuliah Keahlian Khusus
  {
    id: "kalkulus-lanjut",
    name: "Kalkulus Lanjut",
    color: "#1e40af",
    description: "Kalkulus multivariabel dan persamaan diferensial",
    category: "mathematics",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Advanced Calculus",
      id: "Kalkulus Lanjut",
    },
    prerequisites: ["matematika-dasar"],
    tags: ["multivariabel", "diferensial", "integral-ganda", "vektor"],
    defaultSchedule: {
      day: ["monday", "thursday"],
      duration: 100,
      frequency: "weekly",
    },
  },
  {
    id: "pemrograman-web",
    name: "Pemrograman Web",
    color: "#059669",
    description: "HTML, CSS, JavaScript, dan framework web",
    category: "technology",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Web Programming",
      id: "Pemrograman Web",
    },
    prerequisites: ["algoritma-pemrograman"],
    tags: ["html", "css", "javascript", "framework"],
    defaultSchedule: {
      day: ["wednesday", "friday"],
      duration: 150,
      frequency: "weekly",
    },
  },
  {
    id: "kecerdasan-buatan",
    name: "Kecerdasan Buatan",
    color: "#7c3aed",
    description: "Machine learning dan AI fundamentals",
    category: "technology",
    isCore: false,
    educationLevels: ["kuliah"],
    localizedName: {
      en: "Artificial Intelligence",
      id: "Kecerdasan Buatan",
    },
    prerequisites: ["struktur-data", "statistika"],
    tags: ["machine-learning", "neural-network", "deep-learning", "nlp"],
    defaultSchedule: {
      day: ["tuesday", "thursday"],
      duration: 100,
      frequency: "weekly",
    },
  },
];

export async function getPack(): Promise<SubjectPack> {
  return {
    country: "indonesia",
    year: 2025,
    educationLevel: "kuliah",
    subjects,
    metadata: {
      version: "1.0.0",
      lastUpdated: "2025-01-09",
      curriculum: "Kurikulum Perguruan Tinggi Indonesia",
      source: "Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi RI",
      contributors: ["TugasCollecter Team", "Tim Kurikulum Perguruan Tinggi"],
    },
  };
}
