import type { SubjectPack, SubjectTemplate } from "../../../shared/types";

const subjects: SubjectTemplate[] = [
  // Mata Pelajaran Wajib Kelompok A (Wajib Umum)
  {
    id: "pendidikan-agama-sma",
    name: "Pendidikan Agama dan Budi Pekerti",
    color: "#6366f1",
    description: "Pendidikan agama dan pembentukan karakter tingkat SMA",
    category: "religious",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "Religious and Character Education",
      id: "Pendidikan Agama dan Budi Pekerti",
    },
    tags: ["agama", "etika", "moral", "spiritualitas"],
    defaultSchedule: {
      day: ["monday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "ppkn-sma",
    name: "PPKn (Pendidikan Pancasila dan Kewarganegaraan)",
    color: "#dc2626",
    description: "Pendidikan kewarganegaraan dan konstitusi",
    category: "social",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "Civic Education",
      id: "Pendidikan Pancasila dan Kewarganegaraan",
    },
    tags: ["pancasila", "konstitusi", "demokrasi", "ham"],
    defaultSchedule: {
      day: ["tuesday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "bahasa-indonesia-sma",
    name: "Bahasa Indonesia",
    color: "#dc2626",
    description: "Bahasa dan sastra Indonesia tingkat lanjut",
    category: "language",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "Indonesian Language",
      id: "Bahasa Indonesia",
    },
    tags: ["sastra", "linguistik", "retorika", "kritik"],
    defaultSchedule: {
      day: ["monday", "wednesday", "friday"],
      duration: 45,
      frequency: "weekly",
    },
  },
  {
    id: "matematika-sma-wajib",
    name: "Matematika (Wajib)",
    color: "#3b82f6",
    description: "Matematika dasar untuk semua jurusan",
    category: "mathematics",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "Mathematics (Mandatory)",
      id: "Matematika (Wajib)",
    },
    tags: ["aljabar", "trigonometri", "kalkulus", "statistika"],
    defaultSchedule: {
      day: ["tuesday", "thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "sejarah-indonesia-sma",
    name: "Sejarah Indonesia",
    color: "#92400e",
    description: "Sejarah Indonesia dari masa prasejarah hingga reformasi",
    category: "social",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "Indonesian History",
      id: "Sejarah Indonesia",
    },
    tags: ["prasejarah", "kemerdekaan", "orde-baru", "reformasi"],
    defaultSchedule: {
      day: ["wednesday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "bahasa-inggris-sma",
    name: "Bahasa Inggris",
    color: "#10b981",
    description: "Bahasa Inggris tingkat menengah atas",
    category: "language",
    isCore: true,
    educationLevels: ["sma"],
    localizedName: {
      en: "English",
      id: "Bahasa Inggris",
    },
    tags: ["literature", "academic-writing", "communication", "toefl"],
    defaultSchedule: {
      day: ["monday", "thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },

  // Mata Pelajaran Wajib Kelompok B (Wajib)
  {
    id: "seni-budaya-sma",
    name: "Seni Budaya",
    color: "#ec4899",
    description: "Apresiasi dan ekspresi seni budaya Indonesia",
    category: "arts",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Arts and Culture",
      id: "Seni Budaya",
    },
    tags: ["apresiasi", "ekspresi", "budaya-indonesia", "kreativitas"],
    defaultSchedule: {
      day: ["friday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "penjas-sma",
    name: "PENJAS (Pendidikan Jasmani, Olahraga, dan Kesehatan)",
    color: "#06b6d4",
    description: "Pendidikan jasmani dan kesehatan tingkat SMA",
    category: "physical",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Physical Education, Sports and Health",
      id: "Pendidikan Jasmani, Olahraga, dan Kesehatan",
    },
    tags: ["atletik", "permainan", "kesehatan", "kebugaran"],
    defaultSchedule: {
      day: ["wednesday", "friday"],
      duration: 45,
      frequency: "weekly",
    },
  },
  {
    id: "prakarya-kewirausahaan-sma",
    name: "Prakarya dan Kewirausahaan",
    color: "#7c3aed",
    description: "Keterampilan praktis dan jiwa kewirausahaan",
    category: "technology",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Crafts and Entrepreneurship",
      id: "Prakarya dan Kewirausahaan",
    },
    tags: ["keterampilan", "inovasi", "bisnis", "ekonomi-kreatif"],
    defaultSchedule: {
      day: ["thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },

  // Mata Pelajaran Peminatan IPA
  {
    id: "matematika-peminatan",
    name: "Matematika (Peminatan)",
    color: "#1e40af",
    description: "Matematika lanjutan untuk jurusan IPA",
    category: "mathematics",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Mathematics (Specialization)",
      id: "Matematika (Peminatan)",
    },
    tags: ["kalkulus", "vektor", "matriks", "diferensial"],
    defaultSchedule: {
      day: ["monday", "wednesday", "friday"],
      duration: 45,
      frequency: "weekly",
    },
  },
  {
    id: "fisika",
    name: "Fisika",
    color: "#dc2626",
    description: "Mekanika, termodinamika, gelombang, dan fisika modern",
    category: "science",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Physics",
      id: "Fisika",
    },
    tags: ["mekanika", "termodinamika", "gelombang", "kuantum"],
    defaultSchedule: {
      day: ["tuesday", "thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "kimia",
    name: "Kimia",
    color: "#7c3aed",
    description: "Kimia organik, anorganik, dan fisikokimia",
    category: "science",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Chemistry",
      id: "Kimia",
    },
    tags: ["organik", "anorganik", "fisikokimia", "stoikiometri"],
    defaultSchedule: {
      day: ["monday", "wednesday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "biologi",
    name: "Biologi",
    color: "#166534",
    description: "Biologi sel, genetika, ekologi, dan evolusi",
    category: "science",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Biology",
      id: "Biologi",
    },
    tags: ["sel", "genetika", "ekologi", "evolusi"],
    defaultSchedule: {
      day: ["tuesday", "friday"],
      duration: 90,
      frequency: "weekly",
    },
  },

  // Mata Pelajaran Peminatan IPS
  {
    id: "geografi",
    name: "Geografi",
    color: "#0d9488",
    description: "Geografi fisik, manusia, dan regional",
    category: "social",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Geography",
      id: "Geografi",
    },
    tags: ["fisik", "manusia", "regional", "lingkungan"],
    defaultSchedule: {
      day: ["monday", "thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "sejarah",
    name: "Sejarah",
    color: "#92400e",
    description: "Sejarah dunia dan metodologi sejarah",
    category: "social",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "History",
      id: "Sejarah",
    },
    tags: ["dunia", "metodologi", "historiografi", "peradaban"],
    defaultSchedule: {
      day: ["tuesday", "friday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "sosiologi",
    name: "Sosiologi",
    color: "#059669",
    description: "Struktur sosial, perubahan sosial, dan masalah sosial",
    category: "social",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Sociology",
      id: "Sosiologi",
    },
    tags: ["struktur", "perubahan", "masalah", "interaksi"],
    defaultSchedule: {
      day: ["wednesday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "ekonomi",
    name: "Ekonomi",
    color: "#d97706",
    description: "Mikroekonomi, makroekonomi, dan ekonomi pembangunan",
    category: "social",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Economics",
      id: "Ekonomi",
    },
    tags: ["mikro", "makro", "pembangunan", "pasar"],
    defaultSchedule: {
      day: ["wednesday", "friday"],
      duration: 90,
      frequency: "weekly",
    },
  },

  // Mata Pelajaran Peminatan Bahasa
  {
    id: "bahasa-asing-lain",
    name: "Bahasa Asing Lain",
    color: "#16a34a",
    description: "Bahasa asing ketiga (Arab, Jepang, Mandarin, dll)",
    category: "language",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Other Foreign Language",
      id: "Bahasa Asing Lain",
    },
    tags: ["komunikasi", "budaya", "grammar", "conversation"],
    defaultSchedule: {
      day: ["monday", "thursday"],
      duration: 90,
      frequency: "weekly",
    },
  },
  {
    id: "antropologi",
    name: "Antropologi",
    color: "#7c2d12",
    description: "Studi tentang budaya dan masyarakat manusia",
    category: "social",
    isCore: false,
    educationLevels: ["sma"],
    localizedName: {
      en: "Anthropology",
      id: "Antropologi",
    },
    tags: ["budaya", "masyarakat", "etnografi", "evolusi"],
    defaultSchedule: {
      day: ["tuesday"],
      duration: 90,
      frequency: "weekly",
    },
  },
];

export async function getPack(): Promise<SubjectPack> {
  return {
    country: "indonesia",
    year: 2025,
    educationLevel: "sma",
    subjects,
    metadata: {
      version: "1.0.0",
      lastUpdated: "2025-01-09",
      curriculum: "Kurikulum 2013 - SMA",
      source: "Kementerian Pendidikan dan Kebudayaan RI",
      contributors: ["TugasCollecter Team", "Tim Kurikulum Indonesia"],
    },
  };
}
